Outlier IQR

In [3]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

from Outlier_Zscore_std_deviation import lower_limit
%matplotlib inline
import seaborn as sns

In [4]:
df = pd.read_csv(r"C:\Users\amitd\OneDrive\Documents\GitHub\AI_LEARNINGS\Outlier_IQR\weight-height.csv")
df.head()

  Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [5]:
df.shape

(10000, 3)

In [6]:
df.describe()

             Height        Weight
count  10000.000000  10000.000000
mean      66.367560    161.440357
std        3.847528     32.108439
min       54.263133     64.700127
25%       63.505620    135.818051
50%       66.318070    161.212928
75%       69.174262    187.169525
max       78.998742    269.989699

In [16]:
df1 = df[['Gender','Weight']]
Q1 = df1['Weight'].quantile(0.25)
Q3 = df1['Weight'].quantile(0.75)
IQR = Q3 - Q1
Q3,Q1,IQR

(np.float64(187.16952486868348),
 np.float64(135.8180513055015),
 np.float64(51.35147356318197))

In [17]:
upper_limit = Q3 + 1.5*IQR
lower_limit = Q1 - 1.5*IQR
lower_limit,upper_limit

(np.float64(58.79084096072856), np.float64(264.19673521345646))

In [19]:
df1[(df1['Weight']>upper_limit)|(df1['Weight']<lower_limit)]

     Gender      Weight
2014   Male  269.989699

In [21]:
df2 = df1[(df1['Weight']<upper_limit)&(df1['Weight']>lower_limit)]
df2.head()

  Gender      Weight
0   Male  241.893563
1   Male  162.310473
2   Male  212.740856
3   Male  220.042470
4   Male  206.349801

In [22]:
df3 = df[['Gender','Height']]
df3.head()

  Gender     Height
0   Male  73.847017
1   Male  68.781904
2   Male  74.110105
3   Male  71.730978
4   Male  69.881796

In [23]:
a = df3.shape; b = df3.describe()
a,b

((10000, 2),
              Height
 count  10000.000000
 mean      66.367560
 std        3.847528
 min       54.263133
 25%       63.505620
 50%       66.318070
 75%       69.174262
 max       78.998742)

In [24]:
Q1 = df3['Height'].quantile(0.25)
Q3 = df3['Height'].quantile(0.75)
IQR = Q3 - Q1
Q1,Q3,IQR

(np.float64(63.505620481218955),
 np.float64(69.1742617268347),
 np.float64(5.668641245615746))

In [25]:
lower_limit = Q1 - 1.5*IQR
upper_limit = Q3 + 1.5*IQR
lower_limit,upper_limit

(np.float64(55.00265861279534), np.float64(77.67722359525831))

In [26]:
df3[(df3['Height']>upper_limit)|(df3['Height']<lower_limit)]

      Gender     Height
994     Male  78.095867
1317    Male  78.462053
2014    Male  78.998742
3285    Male  78.528210
3757    Male  78.621374
6624  Female  54.616858
7294  Female  54.873728
9285  Female  54.263133

In [27]:
df4 = df3[(df3['Height']<upper_limit)&(df3['Height']>lower_limit)]
df4.head()

  Gender     Height
0   Male  73.847017
1   Male  68.781904
2   Male  74.110105
3   Male  71.730978
4   Male  69.881796